import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Main } from "../src/components/Home";
import { Font } from "../src/types";
import { FontCategory } from "../src/font-categories";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Main
          fonts={[] as Font[]}
          totalFontsAmount={0}
          fontsPerPageAmount={5}
          selectedCategory={FontCategory.ALL}
          currentPage={1}
          onCategoryChange={() => undefined}
          onPageChange={() => undefined}
          onFontDownload={() => undefined}
          onFontDeletion={() => undefined}
        />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
