import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Main } from "../src/components/Home";
import { Font } from "../src/types";
import { FontCategory } from "../src/font-categories";
import { DataStore } from "aws-amplify";
import { Font as _Font } from "../src/models";

type HomeProps = {
  fonts: _Font[];
};

const Home: NextPage<HomeProps> = ({ fonts }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p> {JSON.stringify(fonts)}</p>
      <main>
        <Main
          fonts={[] as Font[]}
          totalFontsAmount={0}
          fontsPerPageAmount={5}
          selectedCategory={FontCategory.ALL}
          currentPage={1}
          onCategoryChange={() => undefined}
          onPageChange={() => undefined}
          onFontDownload={() => undefined}
          onFontDeletion={() => undefined}
        />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const fonts = await DataStore.query(_Font);

  return {
    props: {
      fonts,
    },
  };
};
