/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_appsync_graphqlEndpoint": "https://os366nuo5nh2vezyj7batlpa5e.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vs3setueqnd6fdqaq6zcpvj4hm",
    "aws_cognito_identity_pool_id": "eu-north-1:46e18491-1267-47b9-b684-3c2a0909b676",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_DBmsZ9XVf",
    "aws_user_pools_web_client_id": "3h5kja7ijqfsdo29889tqjr692",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "fonts-website-ng-storage-3bf2fba090117-staging",
    "aws_user_files_s3_bucket_region": "eu-north-1"
};


export default awsmobile;
